import React from 'react';
import Flags from 'react-world-flags';

const countryOptions = [
  { value: 'Afghanistan', label: <><Flags code="AF" style={{ width: 20, marginRight: 10 }} />Afghanistan</> },
  { value: 'Albania', label: <><Flags code="AL" style={{ width: 20, marginRight: 10 }} />Albania</> },
  { value: 'Algeria', label: <><Flags code="DZ" style={{ width: 20, marginRight: 10 }} />Algeria</> },
  { value: 'Andorra', label: <><Flags code="AD" style={{ width: 20, marginRight: 10 }} />Andorra</> },
  { value: 'Angola', label: <><Flags code="AO" style={{ width: 20, marginRight: 10 }} />Angola</> },
  { value: 'Argentina', label: <><Flags code="AR" style={{ width: 20, marginRight: 10 }} />Argentina</> },
  { value: 'Armenia', label: <><Flags code="AM" style={{ width: 20, marginRight: 10 }} />Armenia</> },
  { value: 'Australia', label: <><Flags code="AU" style={{ width: 20, marginRight: 10 }} />Australia</> },
  { value: 'Austria', label: <><Flags code="AT" style={{ width: 20, marginRight: 10 }} />Austria</> },
  { value: 'Azerbaijan', label: <><Flags code="AZ" style={{ width: 20, marginRight: 10 }} />Azerbaijan</> },
  { value: 'Bangladesh', label: <><Flags code="BD" style={{ width: 20, marginRight: 10 }} />Bangladesh</> },
  { value: 'Barbados', label: <><Flags code="BB" style={{ width: 20, marginRight: 10 }} />Barbados</> },
  { value: 'Belarus', label: <><Flags code="BY" style={{ width: 20, marginRight: 10 }} />Belarus</> },
  { value: 'Belgium', label: <><Flags code="BE" style={{ width: 20, marginRight: 10 }} />Belgium</> },
  { value: 'Belize', label: <><Flags code="BZ" style={{ width: 20, marginRight: 10 }} />Belize</> },
  { value: 'Benin', label: <><Flags code="BJ" style={{ width: 20, marginRight: 10 }} />Benin</> },
  { value: 'Bhutan', label: <><Flags code="BT" style={{ width: 20, marginRight: 10 }} />Bhutan</> },
  { value: 'Bolivia', label: <><Flags code="BO" style={{ width: 20, marginRight: 10 }} />Bolivia</> },
  { value: 'Bosnia and Herzegovina', label: <><Flags code="BA" style={{ width: 20, marginRight: 10 }} />Bosnia and Herzegovina</> },
  { value: 'Botswana', label: <><Flags code="BW" style={{ width: 20, marginRight: 10 }} />Botswana</> },
  { value: 'Brazil', label: <><Flags code="BR" style={{ width: 20, marginRight: 10 }} />Brazil</> },
  { value: 'Brunei', label: <><Flags code="BN" style={{ width: 20, marginRight: 10 }} />Brunei</> },
  { value: 'Bulgaria', label: <><Flags code="BG" style={{ width: 20, marginRight: 10 }} />Bulgaria</> },
  { value: 'Burkina Faso', label: <><Flags code="BF" style={{ width: 20, marginRight: 10 }} />Burkina Faso</> },
  { value: 'Burundi', label: <><Flags code="BI" style={{ width: 20, marginRight: 10 }} />Burundi</> },
  { value: 'Cambodia', label: <><Flags code="KH" style={{ width: 20, marginRight: 10 }} />Cambodia</> },
  { value: 'Cameroon', label: <><Flags code="CM" style={{ width: 20, marginRight: 10 }} />Cameroon</> },
  { value: 'Canada', label: <><Flags code="CA" style={{ width: 20, marginRight: 10 }} />Canada</> },
  { value: 'Chile', label: <><Flags code="CL" style={{ width: 20, marginRight: 10 }} />Chile</> },
  { value: 'China', label: <><Flags code="CN" style={{ width: 20, marginRight: 10 }} />China</> },
  { value: 'Colombia', label: <><Flags code="CO" style={{ width: 20, marginRight: 10 }} />Colombia</> },
  { value: 'Costa Rica', label: <><Flags code="CR" style={{ width: 20, marginRight: 10 }} />Costa Rica</> },
  { value: 'Ivory Coast', label: <><Flags code="CI" style={{ width: 20, marginRight: 10 }} />Ivory Coast</> },
  { value: 'Croatia', label: <><Flags code="HR" style={{ width: 20, marginRight: 10 }} />Croatia</> },
  { value: 'Cuba', label: <><Flags code="CU" style={{ width: 20, marginRight: 10 }} />Cuba</> },
  { value: 'Cyprus', label: <><Flags code="CY" style={{ width: 20, marginRight: 10 }} />Cyprus</> },
  { value: 'Czech Republic', label: <><Flags code="CZ" style={{ width: 20, marginRight: 10 }} />Czech Republic</> },
  { value: 'Denmark', label: <><Flags code="DK" style={{ width: 20, marginRight: 10 }} />Denmark</> },
  { value: 'Ecuador', label: <><Flags code="EC" style={{ width: 20, marginRight: 10 }} />Ecuador</> },
  { value: 'Egypt', label: <><Flags code="EG" style={{ width: 20, marginRight: 10 }} />Egypt</> },
  { value: 'France', label: <><Flags code="FR" style={{ width: 20, marginRight: 10 }} />France</> },
  { value: 'Germany', label: <><Flags code="DE" style={{ width: 20, marginRight: 10 }} />Germany</> },
  { value: 'Ghana', label: <><Flags code="GH" style={{ width: 20, marginRight: 10 }} />Ghana</> },
  { value: 'India', label: <><Flags code="IN" style={{ width: 20, marginRight: 10 }} />India</> },
  { value: 'Japan', label: <><Flags code="JP" style={{ width: 20, marginRight: 10 }} />Japan</> },
  { value: 'Israel', label: <><Flags code="IL" style={{ width: 20, marginRight: 10 }} />Israel</> },
  { value: 'Sri Lanka', label: <><Flags code="LK" style={{ width: 20, marginRight: 10 }} />Sri Lanka</> },
  { value: 'Saudi Arabia', label: <><Flags code="SA" style={{ width: 20, marginRight: 10 }} />Saudi Arabia</> },
  { value: 'Somalia', label: <><Flags code="SO" style={{ width: 20, marginRight: 10 }} />Somalia</> },
  { value: 'South Africa', label: <><Flags code="ZA" style={{ width: 20, marginRight: 10 }} />South Africa</> },
  { value: 'United States', label: <><Flags code="US" style={{ width: 20, marginRight: 10 }} />United States</> },
  { value: 'Zimbabwe', label: <><Flags code="ZM" style={{ width: 20, marginRight: 10 }} />Zimbabwe</> },
];
export default countryOptions;